-- Split the previously over-broad Seedance contract into exact T2V/R2V and I2V routes.
-- This migration is additive and data-preserving: no jobs, artifacts, proofs, or credentials are deleted.

START TRANSACTION;

UPDATE `model_registry_entries`
SET
  `display_name` = 'Seedance V1 Fast',
  `category` = 'video',
  `primary_role` = 'video_generation',
  `supports_video_generation` = 1,
  `capabilities_json` = '["video_generation","video_to_video"]',
  `source` = 'static_verified',
  `catalog_completeness` = 'curated_fallback_only',
  `model_owner` = 'bytedance',
  `provider_raw_type` = 'video',
  `provider_raw_category` = 'video',
  `raw_metadata` = '{"compatibility":{"category":"video","taskType":"video","capabilities":["video_generation","video_to_video"],"modalitiesIn":["text","video"],"modalitiesOut":["video"],"transportProfile":"async_job_poll","endpointFamily":"genx_generation_v1","endpointShapeKnown":true,"requestShapeKnown":true,"responseShapeKnown":true,"providerClientExists":true,"workerExecutorExists":true}}',
  `current_availability` = 'available',
  `endpoint_family` = 'genx_generation_v1',
  `transport_profile` = 'async_job_poll',
  `compatibility_version` = 'transport-task-v1',
  `deprecated` = 0,
  `replacement_model` = '',
  `enabled` = 1,
  `notes` = 'GenX Seedance text-to-video and reference-video route. Source images are not sent to this text-only model.'
WHERE `provider` = 'genx'
  AND `model_id` = 'seedance-v1-fast';

INSERT INTO `model_registry_entries` (
  `provider`,
  `model_id`,
  `display_name`,
  `family`,
  `category`,
  `primary_role`,
  `cost_tier`,
  `quality_tier`,
  `latency_tier`,
  `context_window`,
  `supports_video_generation`,
  `capabilities_json`,
  `source`,
  `catalog_completeness`,
  `is_live_discovered`,
  `model_owner`,
  `provider_raw_type`,
  `provider_raw_category`,
  `raw_metadata`,
  `current_availability`,
  `account_access`,
  `endpoint_family`,
  `transport_profile`,
  `structured_output_modes`,
  `supported_parameters`,
  `compatibility_version`,
  `deprecated`,
  `replacement_model`,
  `pricing_source`,
  `pricing_confidence`,
  `pricing_unit`,
  `pricing_currency`,
  `pricing_raw_metadata`,
  `pricing_blocker`,
  `enabled`,
  `hidden`,
  `notes`,
  `safety_tags`,
  `created_at`,
  `updated_at`
) VALUES (
  'genx',
  'seedance-v1-fast-i2v',
  'Seedance V1 Fast I2V',
  'seedance',
  'video',
  'image_to_video',
  'high',
  'balanced',
  'medium',
  0,
  1,
  '["image_to_video"]',
  'static_verified',
  'curated_fallback_only',
  0,
  'bytedance',
  'image-to-video',
  'image-to-video',
  '{"compatibility":{"category":"video","taskType":"image-to-video","capabilities":["image_to_video"],"modalitiesIn":["text","image"],"modalitiesOut":["video"],"transportProfile":"async_job_poll","endpointFamily":"genx_generation_v1","endpointShapeKnown":true,"requestShapeKnown":true,"responseShapeKnown":true,"providerClientExists":true,"workerExecutorExists":true}}',
  'available',
  'unknown',
  'genx_generation_v1',
  'async_job_poll',
  '[]',
  '[]',
  'transport-task-v1',
  0,
  '',
  'unknown',
  'unknown',
  '',
  '',
  '{}',
  'pricing_unknown',
  1,
  0,
  'GenX Seedance image-to-video route. Requires an authorised source image artifact and never uses the text-to-video endpoint.',
  '',
  CURRENT_TIMESTAMP(3),
  CURRENT_TIMESTAMP(3)
)
ON DUPLICATE KEY UPDATE
  `display_name` = VALUES(`display_name`),
  `family` = VALUES(`family`),
  `category` = VALUES(`category`),
  `primary_role` = VALUES(`primary_role`),
  `cost_tier` = VALUES(`cost_tier`),
  `quality_tier` = VALUES(`quality_tier`),
  `latency_tier` = VALUES(`latency_tier`),
  `context_window` = VALUES(`context_window`),
  `supports_video_generation` = VALUES(`supports_video_generation`),
  `capabilities_json` = VALUES(`capabilities_json`),
  `source` = VALUES(`source`),
  `catalog_completeness` = VALUES(`catalog_completeness`),
  `model_owner` = VALUES(`model_owner`),
  `provider_raw_type` = VALUES(`provider_raw_type`),
  `provider_raw_category` = VALUES(`provider_raw_category`),
  `raw_metadata` = VALUES(`raw_metadata`),
  `current_availability` = VALUES(`current_availability`),
  `endpoint_family` = VALUES(`endpoint_family`),
  `transport_profile` = VALUES(`transport_profile`),
  `compatibility_version` = VALUES(`compatibility_version`),
  `deprecated` = VALUES(`deprecated`),
  `replacement_model` = VALUES(`replacement_model`),
  `enabled` = VALUES(`enabled`),
  `hidden` = VALUES(`hidden`),
  `notes` = VALUES(`notes`),
  `updated_at` = CURRENT_TIMESTAMP(3);

COMMIT;
