import { prisma } from '@amarktai/db'

export interface ModelCatalogEntry {
  provider: string
  modelId: string
  displayName: string
  family: string
  category: string
  primaryRole: string
  costTier: string
  latencyTier: string
  contextWindow: number
  capabilities: Record<string, boolean>
  estimatedUnitCost: number | null
  qualityTier: string
  notes: string
}

// Curated seed catalog — source = curated_seed
// These are known models from approved providers as of 2026-07
export const CURATED_MODEL_CATALOG: ModelCatalogEntry[] = [
  // ── Groq: fast low-cost text/tool/speech ─────────────────────────────────
  {
    provider: 'groq',
    modelId: 'llama-3.3-70b-versatile',
    displayName: 'Llama 3.3 70B Versatile',
    family: 'llama',
    category: 'text',
    primaryRole: 'chat',
    costTier: 'very_low',
    latencyTier: 'ultra_low',
    contextWindow: 131072,
    capabilities: { supportsChat: true, supportsText: true, supportsReasoning: true, supportsToolUse: true, supportsStructuredOutput: true },
    estimatedUnitCost: 0.00000059,
    qualityTier: 'standard',
    notes: 'Primary Groq chat model. Ultra-low latency.',
  },
  {
    provider: 'groq',
    modelId: 'llama-3.1-8b-instant',
    displayName: 'Llama 3.1 8B Instant',
    family: 'llama',
    category: 'text',
    primaryRole: 'chat',
    costTier: 'very_low',
    latencyTier: 'ultra_low',
    contextWindow: 131072,
    capabilities: { supportsChat: true, supportsText: true },
    estimatedUnitCost: 0.00000005,
    qualityTier: 'draft',
    notes: 'Fastest Groq model. Good for drafts and simple tasks.',
  },
  {
    provider: 'groq',
    modelId: 'mixtral-8x7b-32768',
    displayName: 'Mixtral 8x7B',
    family: 'mixtral',
    category: 'text',
    primaryRole: 'chat',
    costTier: 'very_low',
    latencyTier: 'ultra_low',
    contextWindow: 32768,
    capabilities: { supportsChat: true, supportsText: true, supportsCode: true },
    estimatedUnitCost: 0.00000024,
    qualityTier: 'standard',
    notes: 'Good general-purpose model with code support.',
  },
  {
    provider: 'groq',
    modelId: 'whisper-large-v3',
    displayName: 'Whisper Large V3',
    family: 'whisper',
    category: 'audio',
    primaryRole: 'stt',
    costTier: 'low',
    latencyTier: 'low',
    contextWindow: 0,
    capabilities: { supportsStt: true },
    estimatedUnitCost: 0.000111,
    qualityTier: 'standard',
    notes: 'Speech-to-text. Cost per audio minute.',
  },
  {
    provider: 'groq',
    modelId: 'whisper-large-v3-turbo',
    displayName: 'Whisper Large V3 Turbo',
    family: 'whisper',
    category: 'audio',
    primaryRole: 'stt',
    costTier: 'very_low',
    latencyTier: 'ultra_low',
    contextWindow: 0,
    capabilities: { supportsStt: true },
    estimatedUnitCost: 0.00004,
    qualityTier: 'draft',
    notes: 'Faster cheaper STT.',
  },
  {
    provider: 'groq',
    modelId: 'playai-tts',
    displayName: 'PlayAI TTS',
    family: 'playai',
    category: 'audio',
    primaryRole: 'tts',
    costTier: 'low',
    latencyTier: 'low',
    contextWindow: 0,
    capabilities: { supportsTts: true },
    estimatedUnitCost: 0.00005,
    qualityTier: 'standard',
    notes: 'Groq TTS. Cost per character.',
  },
  {
    provider: 'groq',
    modelId: 'llama-3.2-11b-vision-preview',
    displayName: 'Llama 3.2 11B Vision',
    family: 'llama',
    category: 'multimodal',
    primaryRole: 'vision',
    costTier: 'very_low',
    latencyTier: 'ultra_low',
    contextWindow: 131072,
    capabilities: { supportsChat: true, supportsText: true, supportsMultimodal: true },
    estimatedUnitCost: 0.00000018,
    qualityTier: 'standard',
    notes: 'Vision/multimodal. OCR and image recognition.',
  },

  // ── Together: broad serverless media/model gateway ───────────────────────
  {
    provider: 'together',
    modelId: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
    displayName: 'Llama 3.1 70B Instruct Turbo',
    family: 'llama',
    category: 'text',
    primaryRole: 'chat',
    costTier: 'low',
    latencyTier: 'low',
    contextWindow: 131072,
    capabilities: { supportsChat: true, supportsText: true, supportsReasoning: true, supportsToolUse: true, supportsStructuredOutput: true },
    estimatedUnitCost: 0.00000088,
    qualityTier: 'standard',
    notes: 'Primary Together chat model.',
  },
  {
    provider: 'together',
    modelId: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
    displayName: 'Llama 3.1 8B Instruct Turbo',
    family: 'llama',
    category: 'text',
    primaryRole: 'chat',
    costTier: 'very_low',
    latencyTier: 'ultra_low',
    contextWindow: 131072,
    capabilities: { supportsChat: true, supportsText: true },
    estimatedUnitCost: 0.00000018,
    qualityTier: 'draft',
    notes: 'Cheap draft chat.',
  },
  {
    provider: 'together',
    modelId: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
    displayName: 'Qwen 2.5 72B Instruct Turbo',
    family: 'qwen',
    category: 'text',
    primaryRole: 'chat',
    costTier: 'low',
    latencyTier: 'low',
    contextWindow: 32768,
    capabilities: { supportsChat: true, supportsText: true, supportsReasoning: true, supportsCode: true, supportsToolUse: true },
    estimatedUnitCost: 0.0000012,
    qualityTier: 'standard',
    notes: 'Strong reasoning and code. Provider = together (not qwen).',
  },
  {
    provider: 'together',
    modelId: 'black-forest-labs/FLUX.1-schnell-Free',
    displayName: 'FLUX.1 Schnell Free',
    family: 'flux',
    category: 'image',
    primaryRole: 'image_generation',
    costTier: 'free',
    latencyTier: 'low',
    contextWindow: 0,
    capabilities: { supportsImageGeneration: true },
    estimatedUnitCost: 0,
    qualityTier: 'draft',
    notes: 'Free tier image generation. Watermarked.',
  },
  {
    provider: 'together',
    modelId: 'black-forest-labs/FLUX.1-schnell',
    displayName: 'FLUX.1 Schnell',
    family: 'flux',
    category: 'image',
    primaryRole: 'image_generation',
    costTier: 'very_low',
    latencyTier: 'low',
    contextWindow: 0,
    capabilities: { supportsImageGeneration: true },
    estimatedUnitCost: 0.003,
    qualityTier: 'standard',
    notes: 'Standard fast image generation.',
  },
  {
    provider: 'together',
    modelId: 'black-forest-labs/FLUX.1-dev',
    displayName: 'FLUX.1 Dev',
    family: 'flux',
    category: 'image',
    primaryRole: 'image_generation',
    costTier: 'low',
    latencyTier: 'medium',
    contextWindow: 0,
    capabilities: { supportsImageGeneration: true },
    estimatedUnitCost: 0.025,
    qualityTier: 'premium',
    notes: 'Higher quality image generation.',
  },
  {
    provider: 'together',
    modelId: 'stabilityai/stable-diffusion-xl-base-1.0',
    displayName: 'Stable Diffusion XL',
    family: 'sdxl',
    category: 'image',
    primaryRole: 'image_generation',
    costTier: 'very_low',
    latencyTier: 'medium',
    contextWindow: 0,
    capabilities: { supportsImageGeneration: true },
    estimatedUnitCost: 0.004,
    qualityTier: 'standard',
    notes: 'Classic SDXL.',
  },
  {
    provider: 'together',
    modelId: 'togethercomputer/MoA-1-Turbo',
    displayName: 'MoA-1 Turbo',
    family: 'moa',
    category: 'text',
    primaryRole: 'chat',
    costTier: 'medium',
    latencyTier: 'medium',
    contextWindow: 32768,
    capabilities: { supportsChat: true, supportsText: true, supportsReasoning: true },
    estimatedUnitCost: 0.000006,
    qualityTier: 'premium',
    notes: 'Mixture of Agents. Higher quality.',
  },
  {
    provider: 'together',
    modelId: 'Gemma-2-27b-it',
    displayName: 'Gemma 2 27B IT',
    family: 'gemma',
    category: 'text',
    primaryRole: 'chat',
    costTier: 'very_low',
    latencyTier: 'low',
    contextWindow: 8192,
    capabilities: { supportsChat: true, supportsText: true },
    estimatedUnitCost: 0.00000028,
    qualityTier: 'standard',
    notes: 'Google Gemma on Together.',
  },
  {
    provider: 'together',
    modelId: 'mistralai/Mixtral-8x22B-Instruct-v0.1',
    displayName: 'Mixtral 8x22B Instruct',
    family: 'mixtral',
    category: 'text',
    primaryRole: 'chat',
    costTier: 'low',
    latencyTier: 'medium',
    contextWindow: 65536,
    capabilities: { supportsChat: true, supportsText: true, supportsCode: true },
    estimatedUnitCost: 0.0000012,
    qualityTier: 'standard',
    notes: 'Large Mixtral. Strong general purpose.',
  },
  {
    provider: 'together',
    modelId: 'togethercomputer/m2-bert-80M-32k-retrieval',
    displayName: 'M2 BERT 80M Retrieval',
    family: 'bert',
    category: 'embeddings',
    primaryRole: 'embeddings',
    costTier: 'very_low',
    latencyTier: 'ultra_low',
    contextWindow: 32768,
    capabilities: { supportsEmbeddings: true },
    estimatedUnitCost: 0.00000001,
    qualityTier: 'standard',
    notes: 'Retrieval embeddings.',
  },
  {
    provider: 'together',
    modelId: 'togethercomputer/m2-bert-80M-8k-retrieval',
    displayName: 'M2 BERT 80M 8K Retrieval',
    family: 'bert',
    category: 'embeddings',
    primaryRole: 'embeddings',
    costTier: 'very_low',
    latencyTier: 'ultra_low',
    contextWindow: 8192,
    capabilities: { supportsEmbeddings: true },
    estimatedUnitCost: 0.00000001,
    qualityTier: 'draft',
    notes: 'Short context embeddings.',
  },

  // ── DeepInfra: expansion gateway ─────────────────────────────────────────
  {
    provider: 'deepinfra',
    modelId: 'Qwen/Qwen2.5-72B-Instruct',
    displayName: 'Qwen 2.5 72B Instruct',
    family: 'qwen',
    category: 'text',
    primaryRole: 'chat',
    costTier: 'low',
    latencyTier: 'medium',
    contextWindow: 32768,
    capabilities: { supportsChat: true, supportsText: true, supportsReasoning: true, supportsCode: true },
    estimatedUnitCost: 0.0000012,
    qualityTier: 'standard',
    notes: 'Provider = deepinfra (not qwen). Blocked until funded.',
  },
  {
    provider: 'deepinfra',
    modelId: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
    displayName: 'Llama 3.1 70B Instruct',
    family: 'llama',
    category: 'text',
    primaryRole: 'chat',
    costTier: 'low',
    latencyTier: 'medium',
    contextWindow: 131072,
    capabilities: { supportsChat: true, supportsText: true },
    estimatedUnitCost: 0.00000052,
    qualityTier: 'standard',
    notes: 'DeepInfra Llama. Blocked until funded.',
  },
  {
    provider: 'deepinfra',
    modelId: 'stabilityai/stable-diffusion-xl-base-1.0',
    displayName: 'Stable Diffusion XL',
    family: 'sdxl',
    category: 'image',
    primaryRole: 'image_generation',
    costTier: 'very_low',
    latencyTier: 'medium',
    contextWindow: 0,
    capabilities: { supportsImageGeneration: true },
    estimatedUnitCost: 0.002,
    qualityTier: 'standard',
    notes: 'DeepInfra SDXL. Blocked until funded.',
  },
  {
    provider: 'deepinfra',
    modelId: 'black-forest-labs/FLUX-1-schnell',
    displayName: 'FLUX.1 Schnell',
    family: 'flux',
    category: 'image',
    primaryRole: 'image_generation',
    costTier: 'very_low',
    latencyTier: 'low',
    contextWindow: 0,
    capabilities: { supportsImageGeneration: true },
    estimatedUnitCost: 0.003,
    qualityTier: 'standard',
    notes: 'DeepInfra FLUX. Blocked until funded.',
  },
  {
    provider: 'deepinfra',
    modelId: ' Wan-AI/Wan2.1-T2V-14B',
    displayName: 'Wan 2.1 T2V 14B',
    family: 'wan',
    category: 'video',
    primaryRole: 'video_generation',
    costTier: 'medium',
    latencyTier: 'high',
    contextWindow: 0,
    capabilities: { supportsVideoGeneration: true },
    estimatedUnitCost: 0.05,
    qualityTier: 'standard',
    notes: 'Wan text-to-video on DeepInfra. Provider = deepinfra (not wan).',
  },
  {
    provider: 'deepinfra',
    modelId: 'PixVerse/PixVerse-V3.5',
    displayName: 'PixVerse V3.5',
    family: 'pixverse',
    category: 'video',
    primaryRole: 'video_generation',
    costTier: 'medium',
    latencyTier: 'high',
    contextWindow: 0,
    capabilities: { supportsVideoGeneration: true },
    estimatedUnitCost: 0.04,
    qualityTier: 'standard',
    notes: 'PixVerse video on DeepInfra. Provider = deepinfra (not pixverse).',
  },
  {
    provider: 'deepinfra',
    modelId: 'Resemble/resemble-enhance',
    displayName: 'Resemble Enhance',
    family: 'resemble',
    category: 'audio',
    primaryRole: 'tts',
    costTier: 'low',
    latencyTier: 'medium',
    contextWindow: 0,
    capabilities: { supportsTts: true },
    estimatedUnitCost: 0.0001,
    qualityTier: 'standard',
    notes: 'DeepInfra TTS. Provider = deepinfra (not resemble).',
  },
  {
    provider: 'deepinfra',
    modelId: 'BAAI/bge-large-en-v1.5',
    displayName: 'BGE Large EN V1.5',
    family: 'bge',
    category: 'embeddings',
    primaryRole: 'embeddings',
    costTier: 'very_low',
    latencyTier: 'ultra_low',
    contextWindow: 512,
    capabilities: { supportsEmbeddings: true },
    estimatedUnitCost: 0.00000001,
    qualityTier: 'standard',
    notes: 'DeepInfra embeddings.',
  },
  {
    provider: 'deepinfra',
    modelId: 'BAAI/bge-reranker-v2-m3',
    displayName: 'BGE Reranker V2 M3',
    family: 'bge',
    category: 'reranking',
    primaryRole: 'reranking',
    costTier: 'very_low',
    latencyTier: 'low',
    contextWindow: 8192,
    capabilities: { supportsReranking: true },
    estimatedUnitCost: 0.00000001,
    qualityTier: 'standard',
    notes: 'DeepInfra reranker.',
  },

  // ── GenX: premium media ──────────────────────────────────────────────────
  {
    provider: 'genx',
    modelId: 'grok-imagine-video',
    displayName: 'Grok Imagine Video',
    family: 'grok',
    category: 'video',
    primaryRole: 'video_generation',
    costTier: 'premium',
    latencyTier: 'high',
    contextWindow: 0,
    capabilities: { supportsVideoGeneration: true },
    estimatedUnitCost: 0.25,
    qualityTier: 'premium',
    notes: 'Primary GenX video model. Premium tier.',
  },
  {
    provider: 'genx',
    modelId: 'grok-imagine-video-hd',
    displayName: 'Grok Imagine Video HD',
    family: 'grok',
    category: 'video',
    primaryRole: 'video_generation',
    costTier: 'premium',
    latencyTier: 'high',
    contextWindow: 0,
    capabilities: { supportsVideoGeneration: true },
    estimatedUnitCost: 0.5,
    qualityTier: 'hero',
    notes: 'HD premium GenX video. Hero tier.',
  },
  {
    provider: 'genx',
    modelId: 'grok-imagine-image',
    displayName: 'Grok Imagine Image',
    family: 'grok',
    category: 'image',
    primaryRole: 'image_generation',
    costTier: 'medium',
    latencyTier: 'medium',
    contextWindow: 0,
    capabilities: { supportsImageGeneration: true },
    estimatedUnitCost: 0.05,
    qualityTier: 'premium',
    notes: 'GenX image generation.',
  },
  {
    provider: 'genx',
    modelId: 'grok-imagine-avatar',
    displayName: 'Grok Imagine Avatar',
    family: 'grok',
    category: 'video',
    primaryRole: 'avatar_generation',
    costTier: 'premium',
    latencyTier: 'high',
    contextWindow: 0,
    capabilities: { supportsVideoGeneration: true },
    estimatedUnitCost: 0.3,
    qualityTier: 'premium',
    notes: 'GenX avatar video.',
  },

  // ── MiMo: coding-tool only ───────────────────────────────────────────────
  {
    provider: 'mimo',
    modelId: 'mimo-coding-agent',
    displayName: 'MiMo Coding Agent',
    family: 'mimo',
    category: 'code',
    primaryRole: 'coding_tool',
    costTier: 'medium',
    latencyTier: 'medium',
    contextWindow: 128000,
    capabilities: { supportsCode: true, supportsToolUse: true },
    estimatedUnitCost: 0.00001,
    qualityTier: 'premium',
    notes: 'CODING_TOOL_ONLY. Not backend runtime. Not Studio. Requires server-side terminal.',
  },
]

export async function seedModelCatalog(): Promise<{ created: number; updated: number }> {
  let created = 0
  let updated = 0

  for (const model of CURATED_MODEL_CATALOG) {
    const existing = await prisma.modelRegistryEntry.findUnique({
      where: { provider_modelId: { provider: model.provider, modelId: model.modelId } },
    })

    if (existing) {
      await prisma.modelRegistryEntry.update({
        where: { id: existing.id },
        data: {
          displayName: model.displayName,
          family: model.family,
          category: model.category,
          primaryRole: model.primaryRole,
          costTier: model.costTier,
          latencyTier: model.latencyTier,
          contextWindow: model.contextWindow,
          estimatedUnitCost: model.estimatedUnitCost,
          notes: model.notes,
          ...model.capabilities,
        },
      })
      updated++
    } else {
      await prisma.modelRegistryEntry.create({
        data: {
          provider: model.provider,
          modelId: model.modelId,
          displayName: model.displayName,
          family: model.family,
          category: model.category,
          primaryRole: model.primaryRole,
          costTier: model.costTier,
          latencyTier: model.latencyTier,
          contextWindow: model.contextWindow,
          estimatedUnitCost: model.estimatedUnitCost,
          notes: model.notes,
          ...model.capabilities,
        },
      })
      created++
    }
  }

  return { created, updated }
}

export async function getModelCatalog(options?: {
  provider?: string
  category?: string
  capability?: string
  enabled?: boolean
}) {
  const where: Record<string, unknown> = {}
  if (options?.provider) where.provider = options.provider
  if (options?.category) where.category = options.category
  if (options?.enabled !== undefined) where.enabled = options.enabled

  const models = await prisma.modelRegistryEntry.findMany({
    where,
    orderBy: [{ provider: 'asc' }, { costTier: 'asc' }],
  })

  if (options?.capability) {
    const capability = options.capability
    return models.filter((m) => {
      const capKey = `supports${capability.charAt(0).toUpperCase()}${capability.slice(1)}`
      return (m as Record<string, unknown>)[capKey] === true
    })
  }

  return models
}
